using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebAPI.Utilities
{
    public static partial class ApplicationConstants
    {

        public struct SPNames
        {
            public const String GetStudentDatas = "GetStudentDatas";
            public const String GetStudentDatasById = "GetStudentDatasById";
            public const String PostStudentData = "PostStudentData";
            public const String PutStudentData = "PutStudentData";
            public const String DeleteStudentData = "DeleteStudentData";
            public const String GetStudents = "GetStudents";
            public const String GetStudentsById = "GetStudentsById";
            public const String PostStudent = "PostStudent";
            public const String PutStudent = "PutStudent";
            public const String DeleteStudent = "DeleteStudent";
            public const String GetOutreachs = "GetOutreachs";
            public const String GetOutreachsById = "GetOutreachsById";
            public const String PostOutreach = "PostOutreach";
            public const String PutOutreach = "PutOutreach";
            public const String DeleteOutreach = "DeleteOutreach";
            public const String GetVroles = "GetVroles";
            public const String GetVrolesById = "GetVrolesById";
            public const String PostVrole = "PostVrole";
            public const String PutVrole = "PutVrole";
            public const String DeleteVrole = "DeleteVrole";
            public const String GetScreens = "GetScreens";
            public const String GetScreensById = "GetScreensById";
            public const String PostScreen = "PostScreen";
            public const String PutScreen = "PutScreen";
            public const String DeleteScreen = "DeleteScreen";
            public const String GetHolidayTypes = "GetHolidayTypes";
            public const String GetHolidayTypesById = "GetHolidayTypesById";
            public const String PostHolidayType = "PostHolidayType";
            public const String PutHolidayType = "PutHolidayType";
            public const String DeleteHolidayType = "DeleteHolidayType";
            public const String GetColors = "GetColors";
            public const String GetColorsById = "GetColorsById";
            public const String PostColor = "PostColor";
            public const String PutColor = "PutColor";
            public const String DeleteColor = "DeleteColor";
            public const String GetCitys = "GetCitys";
            public const String GetCitysById = "GetCitysById";
            public const String PostCity = "PostCity";
            public const String PutCity = "PutCity";
            public const String DeleteCity = "DeleteCity";
            public const String GetSchools = "GetSchools";
            public const String GetSchoolsById = "GetSchoolsById";
            public const String PostSchool = "PostSchool";
            public const String PutSchool = "PutSchool";
            public const String DeleteSchool = "DeleteSchool";
            public const String GetWeekInfos = "GetWeekInfos";
            public const String GetWeekInfosById = "GetWeekInfosById";
            public const String PostWeekInfo = "PostWeekInfo";
            public const String PutWeekInfo = "PutWeekInfo";
            public const String DeleteWeekInfo = "DeleteWeekInfo";
            public const String GetTeachers = "GetTeachers";
            public const String GetTeachersById = "GetTeachersById";
            public const String PostTeacher = "PostTeacher";
            public const String PutTeacher = "PutTeacher";
            public const String DeleteTeacher = "DeleteTeacher";
            public const String GetParameters = "GetParameters";
            public const String GetParametersById = "GetParametersById";
            public const String PostParameter = "PostParameter";
            public const String PutParameter = "PutParameter";
            public const String DeleteParameter = "DeleteParameter";
            public const String GetStandards = "GetStandards";
            public const String GetStandardsById = "GetStandardsById";
            public const String PostStandard = "PostStandard";
            public const String PutStandard = "PutStandard";
            public const String DeleteStandard = "DeleteStandard";
            public const String GetSections = "GetSections";
            public const String GetSectionsById = "GetSectionsById";
            public const String PostSection = "PostSection";
            public const String PutSection = "PutSection";
            public const String DeleteSection = "DeleteSection";
            public const String GetTeams = "GetTeams";
            public const String GetTeamsById = "GetTeamsById";
            public const String PostTeam = "PostTeam";
            public const String PutTeam = "PutTeam";
            public const String DeleteTeam = "DeleteTeam";
            public const String GetHolidays = "GetHolidays";
            public const String GetHolidaysById = "GetHolidaysById";
            public const String PostHoliday = "PostHoliday";
            public const String PutHoliday = "PutHoliday";
            public const String DeleteHoliday = "DeleteHoliday";
            public const String GetVolunteers = "GetVolunteers";
            public const String GetVolunteersById = "GetVolunteersById";
            public const String PostVolunteer = "PostVolunteer";
            public const String PutVolunteer = "PutVolunteer";
            public const String DeleteVolunteer = "DeleteVolunteer";
            public const String GetRoleScreenMappings = "GetRoleScreenMappings";
            public const String GetRoleScreenMappingsById = "GetRoleScreenMappingsById";
            public const String PostRoleScreenMapping = "PostRoleScreenMapping";
            public const String PutRoleScreenMapping = "PutRoleScreenMapping";
            public const String DeleteRoleScreenMapping = "DeleteRoleScreenMapping";
            public const String GetYearInfos = "GetYearInfos";
            public const String GetYearInfosById = "GetYearInfosById";
            public const String PostYearInfo = "PostYearInfo";
            public const String PutYearInfo = "PutYearInfo";
            public const String DeleteYearInfo = "DeleteYearInfo";
            public const String GetMonthInfos = "GetMonthInfos";
            public const String GetMonthInfosById = "GetMonthInfosById";
            public const String PostMonthInfo = "PostMonthInfo";
            public const String PutMonthInfo = "PutMonthInfo";
            public const String DeleteMonthInfo = "DeleteMonthInfo";
            public const String GetDayInfos = "GetDayInfos";
            public const String GetDayInfosById = "GetDayInfosById";
            public const String PostDayInfo = "PostDayInfo";
            public const String PutDayInfo = "PutDayInfo";
            public const String DeleteDayInfo = "DeleteDayInfo";
            public const String GetTeamStudentMappings = "GetTeamStudentMappings";
            public const String GetTeamStudentMappingsById = "GetTeamStudentMappingsById";
            public const String PostTeamStudentMapping = "PostTeamStudentMapping";
            public const String PutTeamStudentMapping = "PutTeamStudentMapping";
            public const String DeleteTeamStudentMapping = "DeleteTeamStudentMapping";
            public const String GetLogins = "GetLogins";
            public const String GetLoginsById = "GetLoginsById";
            public const String PostLogin = "PostLogin";
            public const String PutLogin = "PutLogin";
            public const String DeleteLogin = "DeleteLogin";
            public const String GetTeamWiseTrackings = "GetTeamWiseTrackings";
            public const String GetTeamWiseTrackingsById = "GetTeamWiseTrackingsById";
            public const String PostTeamWiseTracking = "PostTeamWiseTracking";
            public const String PutTeamWiseTracking = "PutTeamWiseTracking";
            public const String DeleteTeamWiseTracking = "DeleteTeamWiseTracking";
            public const String GetExcelDatas = "GetExcelDatas";
            public const String GetExcelDatasById = "GetExcelDatasById";
            public const String PostExcelData = "PostExcelData";
            public const String PutExcelData = "PutExcelData";
            public const String DeleteExcelData = "DeleteExcelData";
            public const String GetClassWiseTrackings = "GetClassWiseTrackings";
            public const String GetClassWiseTrackingsById = "GetClassWiseTrackingsById";
            public const String PostClassWiseTracking = "PostClassWiseTracking";
            public const String PutClassWiseTracking = "PutClassWiseTracking";
            public const String DeleteClassWiseTracking = "DeleteClassWiseTracking";
            public const String GetIndividualTrackings = "GetIndividualTrackings";
            public const String GetIndividualTrackingsById = "GetIndividualTrackingsById";
            public const String PostIndividualTracking = "PostIndividualTracking";
            public const String PutIndividualTracking = "PutIndividualTracking";
            public const String DeleteIndividualTracking = "DeleteIndividualTracking";
            public const String GetComparativeCharts = "GetComparativeCharts";
            public const String GetComparativeChartsById = "GetComparativeChartsById";
            public const String PostComparativeChart = "PostComparativeChart";
            public const String PutComparativeChart = "PutComparativeChart";
            public const String DeleteComparativeChart = "DeleteComparativeChart";
        }

    }
}
